import {CountryCode} from './isdCode'
export class CountryCodes {
    public data = {"93":{"name":"Afghanistan ","code":"AF"},
    "355":{"name":"Albania ","code":"AL"},
    "213":{"name":"Algeria ","code":"DZ"},
    "1-684":{"name":"American Samoa","code":"AS"},
    "376":{"name":"Andorra, Principality of ","code":"AD"},
    "244":{"name":"Angola","code":"AO"},
    "1-264":{"name":"Anguilla ","code":"AI"},
    "672":{"name":"Antarctica","code":"AQ"},
    "1-268":{"name":"Antigua and Barbuda","code":"AG"},
    "54":{"name":"Argentina ","code":"AR"},
    "374":{"name":"Armenia","code":"AM"},
    "297":{"name":"Aruba","code":"AW"},
    "61":{"name":"Australia","code":"AU"},
    "43":{"name":"Austria","code":"AT"},
    "994":{"name":"Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)","code":"AZ"},
    "1-242":{"name":"Bahamas, Commonwealth of The","code":"BS"},
    "973":{"name":"Bahrain, Kingdom of (Former Dilmun)","code":"BH"},
    "880":{"name":"Bangladesh (Former East Pakistan)","code":"BD"},
    "1-246":{"name":"Barbados ","code":"BB"},
    "375":{"name":"Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)","code":"BY"},
    "32":{"name":"Belgium ","code":"BE"},
    "501":{"name":"Belize (Former British Honduras)","code":"BZ"},
    "229":{"name":"Benin (Former Dahomey)","code":"BJ"},
    "1-441":{"name":"Bermuda ","code":"BM"},
    "975":{"name":"Bhutan, Kingdom of","code":"BT"},
    "591":{"name":"Bolivia ","code":"BO"},
    "387":{"name":"Bosnia and Herzegovina ","code":"BA"},
    "267":{"name":"Botswana (Former Bechuanaland)","code":"BW"},
    "55":{"name":"Brazil ","code":"BR"},
    "673":{"name":"Brunei (Negara Brunei Darussalam) ","code":"BN"},
    "359":{"name":"Bulgaria ","code":"BG"},
    "226":{"name":"Burkina Faso (Former Upper Volta)","code":"BF"},
    "257":{"name":"Burundi (Former Urundi)","code":"BI"},
    "855":{"name":"Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)","code":"KH"},
    "237":{"name":"Cameroon (Former French Cameroon)","code":"CM"},
    "238":{"name":"Cape Verde ","code":"CV"},
    "1-345":{"name":"Cayman Islands ","code":"KY"},
    "236":{"name":"Central African Republic ","code":"CF"},
    "235":{"name":"Chad ","code":"TD"},
    "56":{"name":"Chile ","code":"CL"},
    "86":{"name":"China ","code":"CN"},
    "53":{"name":"Christmas Island ","code":"CX"},
    "57":{"name":"Colombia ","code":"CO"},
    "269":{"name":"Comoros, Union of the ","code":"KM"},
    "243":{"name":"Congo, Democratic Republic of the (Former Zaire) ","code":"CD"},
    "242":{"name":"Congo, Republic of the","code":"CG"},
    "682":{"name":"Cook Islands (Former Harvey Islands)","code":"CK"},
    "506":{"name":"Costa Rica ","code":"CR"},
    "225":{"name":"Cote D'Ivoire (Former Ivory Coast) ","code":"CI"},
    "385":{"name":"Croatia (Hrvatska) ","code":"HR"},
    "357":{"name":"Cyprus ","code":"CY"},
    "420":{"name":"Czech Republic","code":"CZ"},
    "45":{"name":"Denmark ","code":"DK"},
    "253":{"name":"Djibouti (Former French Territory of the Afars and Issas, French Somaliland)","code":"DJ"},
    "1-767":{"name":"Dominica ","code":"DM"},
    "1-809 and 1-829  ":{"name":"Dominican Republic ","code":"DO"},
    "670":{"name":"East Timor (Former Portuguese Timor)","code":"TP"},
    "593 ":{"name":"Ecuador ","code":"EC"},
    "20":{"name":"Egypt (Former United Arab Republic - with Syria)","code":"EG"},
    "503":{"name":"El Salvador ","code":"SV"},
    "240":{"name":"Equatorial Guinea (Former Spanish Guinea)","code":"GQ"},
    "291":{"name":"Eritrea (Former Eritrea Autonomous Region in Ethiopia)","code":"ER"},
    "372":{"name":"Estonia (Former Estonian Soviet Socialist Republic)","code":"EE"},
    "251":{"name":"Ethiopia (Former Abyssinia, Italian East Africa)","code":"ET"},
    "500":{"name":"Falkland Islands (Islas Malvinas) ","code":"FK"},
    "298":{"name":"Faroe Islands ","code":"FO"},
    "679":{"name":"Fiji ","code":"FJ"},
    "358":{"name":"Finland ","code":"FI"},
    "33":{"name":"France ","code":"FR"},
    "594":{"name":"French Guiana or French Guyana ","code":"GF"},
    "689":{"name":"French Polynesia (Former French Colony of Oceania)","code":"PF"},
    "241":{"name":"Gabon (Gabonese Republic)","code":"GA"},
    "220":{"name":"Gambia, The ","code":"GM"},
    "995":{"name":"Georgia (Former Georgian Soviet Socialist Republic)","code":"GE"},
    "49":{"name":"Germany ","code":"DE"},
    "233":{"name":"Ghana (Former Gold Coast)","code":"GH"},
    "350":{"name":"Gibraltar ","code":"GI"},
    "30":{"name":"Greece ","code":"GR"},
    "299":{"name":"Greenland ","code":"GL"},
    "1-473":{"name":"Grenada ","code":"GD"},
    "590":{"name":"Guadeloupe","code":"GP"},
    "1-671":{"name":"Guam","code":"GU"},
    "502":{"name":"Guatemala ","code":"GT"},
    "224":{"name":"Guinea (Former French Guinea)","code":"GN"},
    "245":{"name":"Guinea-Bissau (Former Portuguese Guinea)","code":"GW"},
    "592":{"name":"Guyana (Former British Guiana)","code":"GY"},
    "509":{"name":"Haiti ","code":"HT"},
    "504":{"name":"Honduras ","code":"HN"},
    "852":{"name":"Hong Kong ","code":"HK"},
    "36":{"name":"Hungary ","code":"HU"},
    "354":{"name":"Iceland ","code":"IS"},
    "91":{"name":"India ","code":"IN"},
    "62":{"name":"Indonesia (Former Netherlands East Indies; Dutch East Indies)","code":"ID"},
    "98":{"name":"Iran, Islamic Republic of","code":"IR"},
    "964":{"name":"Iraq ","code":"IQ"},
    "353":{"name":"Ireland ","code":"IE"},
    "972":{"name":"Israel ","code":"IL"},
    "39":{"name":"Italy ","code":"IT"},
    "1-876":{"name":"Jamaica ","code":"JM"},
    "81":{"name":"Japan ","code":"JP"},
    "962":{"name":"Jordan (Former Transjordan)","code":"JO"},
    "254":{"name":"Kenya (Former British East Africa)","code":"KE"},
    "686":{"name":"Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)","code":"KI"},
    "850":{"name":"Korea, Democratic People's Republic of (North Korea)","code":"KP"},
    "82":{"name":"Korea, Republic of (South Korea) ","code":"KR"},
    "965":{"name":"Kuwait ","code":"KW"},
    "996":{"name":"Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)","code":"KG"},
    "856":{"name":"Lao People's Democratic Republic (Laos)","code":"LA"},
    "371":{"name":"Latvia (Former Latvian Soviet Socialist Republic)","code":"LV"},
    "961":{"name":"Lebanon ","code":"LB"},
    "266":{"name":"Lesotho (Former Basutoland)","code":"LS"},
    "231":{"name":"Liberia ","code":"LR"},
    "218":{"name":"Libya (Libyan Arab Jamahiriya)","code":"LY"},
    "423":{"name":"Liechtenstein ","code":"LI"},
    "370":{"name":"Lithuania (Former Lithuanian Soviet Socialist Republic)","code":"LT"},
    "352":{"name":"Luxembourg ","code":"LU"},
    "853":{"name":"Macau ","code":"MO"},
    "389":{"name":"Macedonia, The Former Yugoslav Republic of","code":"MK"},
    "261":{"name":"Madagascar (Former Malagasy Republic)","code":"MG"},
    "265":{"name":"Malawi (Former British Central African Protectorate, Nyasaland)","code":"MW"},
    "60":{"name":"Malaysia ","code":"MY"},
    "960":{"name":"Maldives ","code":"MV"},
    "223":{"name":"Mali (Former French Sudan and Sudanese Republic) ","code":"ML"},
    "356":{"name":"Malta ","code":"MT"},
    "692":{"name":"Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)","code":"MH"},
    "596":{"name":"Martinique (French) ","code":"MQ"},
    "222":{"name":"Mauritania ","code":"MR"},
    "230":{"name":"Mauritius ","code":"MU"},
    "52":{"name":"Mexico ","code":"MX"},
    "691":{"name":"Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)","code":"FM"},
    "373":{"name":"Moldova, Republic of","code":"MD"},
    "377":{"name":"Monaco, Principality of","code":"MC"},
    "976":{"name":"Mongolia (Former Outer Mongolia)","code":"MN"},
    "1-664":{"name":"Montserrat ","code":"MS"},
    "212":{"name":"Morocco ","code":"MA"},
    "258":{"name":"Mozambique (Former Portuguese East Africa)","code":"MZ"},
    "95":{"name":"Myanmar, Union of (Former Burma)","code":"MM"},
    "264":{"name":"Namibia (Former German Southwest Africa, South-West Africa)","code":"NA"},
    "674":{"name":"Nauru (Former Pleasant Island)","code":"NR"},
    "977":{"name":"Nepal ","code":"NP"},
    "31":{"name":"Netherlands ","code":"NL"},
    "599":{"name":"Netherlands Antilles (Former Curacao and Dependencies)","code":"AN"},
    "687":{"name":"New Caledonia ","code":"NC"},
    "64":{"name":"New Zealand (Aotearoa) ","code":"NZ"},
    "505":{"name":"Nicaragua ","code":"NI"},
    "227":{"name":"Niger ","code":"NE"},
    "234":{"name":"Nigeria ","code":"NG"},
    "683":{"name":"Niue (Former Savage Island)","code":"NU"},
    "1-670":{"name":"Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)","code":"MP"},
    "47":{"name":"Norway ","code":"NO"},
    "968":{"name":"Oman, Sultanate of (Former Muscat and Oman)","code":"OM"},
    "92":{"name":"Pakistan (Former West Pakistan)","code":"PK"},
    "680":{"name":"Palau (Former Palau District - Trust Terriroty of the Pacific Islands)","code":"PW"},
    "970":{"name":"Palestinian State (Proposed)","code":"PS"},
    "507":{"name":"Panama ","code":"PA"},
    "675":{"name":"Papua New Guinea (Former Territory of Papua and New Guinea)","code":"PG"},
    "595":{"name":"Paraguay ","code":"PY"},
    "51":{"name":"Peru ","code":"PE"},
    "63":{"name":"Philippines ","code":"PH"},
    "48":{"name":"Poland ","code":"PL"},
    "351":{"name":"Portugal ","code":"PT"},
    "1-787 or 1-939":{"name":"Puerto Rico ","code":"PR"},
    "974 ":{"name":"Qatar, State of ","code":"QA"},
    "262":{"name":"Reunion (French) (Former Bourbon Island)","code":"RE"},
    "40":{"name":"Romania ","code":"RO"},
    "7":{"name":"Russian Federation ","code":"RU"},
    "250":{"name":"Rwanda (Rwandese Republic) (Former Ruanda)","code":"RW"},
    "290":{"name":"Saint Helena ","code":"SH"},
    "1-869":{"name":"Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)","code":"KN"},
    "1-758":{"name":"Saint Lucia ","code":"LC"},
    "508":{"name":"Saint Pierre and Miquelon ","code":"PM"},
    "1-784":{"name":"Saint Vincent and the Grenadines ","code":"VC"},
    "685":{"name":"Samoa (Former Western Samoa)","code":"WS"},
    "378":{"name":"San Marino ","code":"SM"},
    "239":{"name":"Sao Tome and Principe ","code":"ST"},
    "966":{"name":"Saudi Arabia ","code":"SA"},
    "221":{"name":"Senegal ","code":"SN"},
    "248":{"name":"Seychelles ","code":"SC"},
    "232":{"name":"Sierra Leone ","code":"SL"},
    "65":{"name":"Singapore ","code":"SG"},
    "421":{"name":"Slovakia","code":"SK"},
    "386":{"name":"Slovenia ","code":"SI"},
    "677":{"name":"Solomon Islands (Former British Solomon Islands)","code":"SB"},
    "252":{"name":"Somalia (Former Somali Republic, Somali Democratic Republic) ","code":"SO"},
    "27":{"name":"South Africa (Former Union of South Africa)","code":"ZA"},
    "34":{"name":"Spain ","code":"ES"},
    "94":{"name":"Sri Lanka (Former Serendib, Ceylon) ","code":"LK"},
    "249":{"name":"Sudan (Former Anglo-Egyptian Sudan) ","code":"SD"},
    "597":{"name":"Suriname (Former Netherlands Guiana, Dutch Guiana)","code":"SR"},
    "268":{"name":"Swaziland, Kingdom of ","code":"SZ"},
    "46":{"name":"Sweden ","code":"SE"},
    "41":{"name":"Switzerland ","code":"CH"},
    "963":{"name":"Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)","code":"SY"},
    "886":{"name":"Taiwan (Former Formosa)","code":"TW"},
    "992":{"name":"Tajikistan (Former Tajik Soviet Socialist Republic)","code":"TJ"},
    "255":{"name":"Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)","code":"TZ"},
    "66":{"name":"Thailand (Former Siam)","code":"TH"},
    "690":{"name":"Tokelau ","code":"TK"},
    "676":{"name":"Tonga, Kingdom of (Former Friendly Islands)","code":"TO"},
    "1-868":{"name":"Trinidad and Tobago ","code":"TT"},
    "216":{"name":"Tunisia ","code":"TN"},
    "90":{"name":"Turkey ","code":"TR"},
    "993":{"name":"Turkmenistan (Former Turkmen Soviet Socialist Republic)","code":"TM"},
    "1-649":{"name":"Turks and Caicos Islands ","code":"TC"},
    "688":{"name":"Tuvalu (Former Ellice Islands)","code":"TV"},
    "256":{"name":"Uganda, Republic of","code":"UG"},
    "380":{"name":"Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)","code":"UA"},
    "971":{"name":"United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)","code":"AE"},
    "44":{"name":"United Kingdom (Great Britain / UK)","code":"GB"},
    "1":{"name":"United States ","code":"US"}, 
    "598":{"name":"Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)","code":"UY"},
    "998":{"name":"Uzbekistan (Former UZbek Soviet Socialist Republic)","code":"UZ"},
    "678":{"name":"Vanuatu (Former New Hebrides)","code":"VU"},
    "418":{"name":"Vatican City State (Holy See)","code":"VA"},
    "58":{"name":"Venezuela ","code":"VE"},
    "84":{"name":"Vietnam ","code":"VN"},
    "1-284":{"name":"Virgin Islands, British ","code":"VI"},
    "1-340":{"name":"Virgin Islands, United States (Former Danish West Indies) ","code":"VQ"},
    "681":{"name":"Wallis and Futuna Islands ","code":"WF"},
    "967":{"name":"Yemen ","code":"YE"},
    "260":{"name":"Zambia, Republic of (Former Northern Rhodesia) ","code":"ZM"},
    "263":{"name":"Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia) ","code":"ZW"}}
    ;
    
    
}